---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include OS-specific tasks.
  include_vars: "{{ ansible_os_family }}.yml"
